from .auth_controller import auth_bp
from .admin_controller import admin_bp
from .usuario_controller import usuario_bp
from .medico_controller import medico_bp
from .paciente_controller import paciente_bp
from .especialidad_controller import especialidad_bp
from .cita_controller import cita_bp
from .consulta_controller import consulta_bp
from .receta_controller import receta_bp
from .servicio_controller import servicio_bp
from .factura_controller import factura_bp
from .configuracion_controller import configuracion_bp